import { z } from "zod";

export const createUserSchema = z.object({
  name: z.string().min(1, "Name is required."),
  email: z.string().email("Valid email is required."),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters."),
}).strict();

/**
 * User IDs are generated by Better Auth — opaque alphanumeric identifiers
 * (~31–32 chars by default; the live database contains only 32-char IDs),
 * optionally UUIDs when configured. Validation must accept the real ID format;
 * a strict UUID check silently rejects every real user ID (this broke both
 * toggleUserActive and assignLead — see Task P-2 Better Auth ID validation).
 * The pattern stays strict: bounded length, alphanumeric plus `-`/`_` (covers
 * UUIDs), no other characters.
 */
export const BETTER_AUTH_USER_ID_PATTERN = /^[A-Za-z0-9_-]{16,64}$/;

export function isValidBetterAuthUserId(userId: unknown): userId is string {
  return typeof userId === "string" && BETTER_AUTH_USER_ID_PATTERN.test(userId);
}

export function buildBetterAuthUserIdSchema(message = "Invalid user ID.") {
  return z.string().regex(BETTER_AUTH_USER_ID_PATTERN, message);
}

export const toggleUserSchema = z.object({
  userId: buildBetterAuthUserIdSchema("Invalid user ID."),
});

export const changePasswordSchema = z
  .object({
    currentPassword: z.string().min(1, "Current password is required."),
    newPassword: z.string().min(8, "Password must be at least 8 characters."),
    confirmPassword: z.string().min(1, "Please confirm your password."),
  })
  .refine((data) => data.newPassword === data.confirmPassword, {
    message: "Passwords do not match.",
    path: ["confirmPassword"],
  });
