-- Align FunnelEvent and QualificationToken with the project's Prisma conventions.
--
-- 20260918000000_add_funnel_events was hand-written rather than generated by Prisma
-- and omitted two details that every Prisma-generated migration in this project
-- includes: ON UPDATE CASCADE on foreign keys, and TIMESTAMP(3) precision. This
-- migration closes that drift.
--
-- The Prisma schema is the source of truth: 14 of 16 foreign keys and 12 of 13
-- application tables already follow these conventions, so aligning these two
-- outliers to the schema is what makes the project internally consistent.
--
-- Non-destructive: no DROP TABLE, no DROP COLUMN, no TRUNCATE, no data rewrite.
-- TIMESTAMP(6) -> TIMESTAMP(3) truncates sub-millisecond precision, which this
-- application never stores — Prisma reads and writes JavaScript Date objects,
-- which are millisecond-precision.
--
-- Runtime behaviour is unchanged either way: ON UPDATE only fires when a Lead.id
-- value is updated, and no code writes a primary key.

-- Timestamp precision: milliseconds, matching every Prisma-generated table.
ALTER TABLE "FunnelEvent" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

ALTER TABLE "QualificationToken"
  ALTER COLUMN "createdAt"  SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "expiresAt"  SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "consumedAt" SET DATA TYPE TIMESTAMP(3);

-- Referential actions: restore the Prisma-default ON UPDATE CASCADE.
ALTER TABLE "FunnelEvent" DROP CONSTRAINT "FunnelEvent_leadId_fkey";
ALTER TABLE "FunnelEvent" ADD CONSTRAINT "FunnelEvent_leadId_fkey"
  FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "QualificationToken" DROP CONSTRAINT "QualificationToken_leadId_fkey";
ALTER TABLE "QualificationToken" ADD CONSTRAINT "QualificationToken_leadId_fkey"
  FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE CASCADE ON UPDATE CASCADE;